name: Compare Upstream

on:
  schedule: 
   - cron: "0 1 * * *"

jobs:
  compare:
    runs-on: ubuntu-latest
    outputs:
      upstream_change: ${{ steps.compare_step.outputs.upstream_change }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Upgrade pip and install mpc_obscodes
      run: python -m pip install --upgrade build requests mpc-obscodes
    - name: Download and Decompress the MPC Observatory Code File
      run: |
        python mpc_obscodes/fetch.py --compressed_file obscodes_extended.json.gz --decompressed_file obscodes_extended.json --md5_file obscodes_extended_new.md5
    - name: Detect Changes to obscodes_extended.json
      id: compare_step
      run: | 
        cp mpc_obscodes/obscodes_extended.md5 . 
        md5sum --check obscodes_extended.md5 && echo 'upstream_change=false' >> $GITHUB_OUTPUT || echo 'upstream_change=true' >> $GITHUB_OUTPUT

  build-test-publish:
    needs: compare
    runs-on: ubuntu-latest
    if: needs.compare.outputs.upstream_change == 'true'
    uses: ./.github/workflows/build_test_publish.yml
